### ISSUE TITLE
JSON or csv

### ISSUE THREAD

**Issue by laurawalexander** [matthewkling/natlas#2]

**Comment by laurawalexander** [comment]
Laura: check for species duplicates in the species list

**Comment by matthewkling** [comment]
bilevel partition that uses JSON:
https://bl.ocks.org/mbostock/4063570

dendrogram using CSV data format:
https://bl.ocks.org/mbostock/5944371

**Comment by laurawalexander** [comment]
@matthewkling Turn CSV to json

**Comment by matthewkling** [comment]
Fixed bug that was placing taxa in wrong category, and regenerated a new json that loads into d3 without throwing a parse error.
