### ISSUE TITLE
Species list venn diagram

### ISSUE THREAD

**Issue by matthewkling** [matthewkling/natlas#3]

**Comment by laurawalexander** [comment]
I need to make a column for who thinks species are present

**Comment by ChristineWilkinson** [comment]
https://jsfiddle.net/datashaman/rBfy5/4/light/

http://bl.ocks.org/josiahdavis/7d84b2f1837eab9c24d9

http://www.adeveloperdiary.com/d3-js/create-stacked-bar-chart-using-d3-js/

https://bl.ocks.org/lucguillemot/756d855b798c77883cf72f2a404e390a

http://bl.ocks.org/kiranml1/6872226

https://codepen.io/nlounds/pen/GzKwt

**Comment by matthewkling** [comment]
Found a template and got it working with our taxonomic json.
